# Generated by Django 5.2.8 on 2025-11-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='core',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.core')),
            ],
        ),
    ]
