# Generated by Django 5.2.8 on 2025-11-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('fuel', 'Fuel'), ('travel', 'Travel')], max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('fuel', 'Fuel'), ('travel', 'Travel')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.core')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2e_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Emissions.activity')),
                ('emission_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Emissions.emissionfactor')),
            ],
        ),
    ]
