# Generated by Django 5.2.8 on 2025-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='facility',
        ),
        migrations.AddField(
            model_name='activity',
            name='core',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='co2e_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='emission_factor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='factor_value',
            field=models.FloatField(),
        ),
    ]
