# Generated by Django 5.2.8 on 2025-11-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emissions', '0002_remove_activity_facility_activity_core_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='core',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Emissions.activity'),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='co2e_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='emission_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Emissions.emissionfactor'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='factor_value',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
