# Generated by Django 5.2.8 on 2025-11-19 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_core_location_alter_core_name_facility'),
        ('Emissions', '0003_alter_activity_core_alter_activity_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='core',
        ),
        migrations.AddField(
            model_name='activity',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.facility'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='convertedemission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emissions.activity'),
        ),
    ]
